spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/building_materials
    username: postgres
    password: yyyyy
  jpa:
    hibernate:
      ddl-auto: update  # use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: backendapp
server:
  address: 127.0.0.1
  port: 8080
